/*
 * Generated by ISE 14.05.9.5158 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F225_5054();
extern void F229_5317();
extern void F223_4981();
extern void F228_5226();
extern void F251_3182();
extern void F249_4861();
extern void F40_700();
extern EIF_REFERENCE F40_687();
extern EIF_BOOLEAN F40_699();
extern EIF_BOOLEAN F40_704();
extern void F40_709();
extern void F40_710();
extern void F40_711();
extern void F58_1006();
extern EIF_TYPED_VALUE F58_1007();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F225_5054;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F223_4981;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F251_3182;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F229_5317;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F228_5226;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F249_4861;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F40_700;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F40_699;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F40_687;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F40_704;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F40_709;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F40_710;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F40_711;

	egc_str_dtype = 228;

	egc_str32_dtype = 227;
	egc_arr_dtype = 250;
	egc_tup_dtype = 177;
	egc_disp_rout_id = 1714;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)345;
	egc_sp_wchar = (EIF_TYPE_INDEX)727;
	egc_sp_bool = (EIF_TYPE_INDEX)690;
	egc_sp_uint8 = (EIF_TYPE_INDEX)603;
	egc_sp_uint16 = (EIF_TYPE_INDEX)552;
	egc_sp_uint32 = (EIF_TYPE_INDEX)485;
	egc_sp_uint64 = (EIF_TYPE_INDEX)445;
	egc_sp_int8 = (EIF_TYPE_INDEX)65535;
	egc_sp_int16 = (EIF_TYPE_INDEX)65535;
	egc_sp_int32 = (EIF_TYPE_INDEX)517;
	egc_sp_int64 = (EIF_TYPE_INDEX)65535;
	egc_sp_real32 = (EIF_TYPE_INDEX)431;
	egc_sp_real64 = (EIF_TYPE_INDEX)396;
	egc_sp_pointer = (EIF_TYPE_INDEX)330;
	egc_sp_ref = (EIF_TYPE_INDEX)238;

	egc_uint8_dtype = 197;
	egc_uint16_dtype = 194;
	egc_uint32_dtype = 191;
	egc_uint64_dtype = 188;
	egc_int8_dtype = 185;
	egc_int16_dtype = 182;
	egc_int32_dtype = 179;
	egc_int64_dtype = 200;
	egc_bool_dtype = 212;
	egc_real32_dtype = 215;
	egc_char_dtype = 209;
	egc_wchar_dtype = 206;
	egc_real64_dtype = 203;
	egc_point_dtype = 218;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 75;
	egc_except_emnger_dtype = 39;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "echo_websocket_server";
	egc_system_location = "C:\\Users\\Manav\\Desktop\\Optional Web Socket\\WebSocket-optional_ssl_support\\server\\example\\echo_websocket_server\\EIFGENs\\echo_websocket_server_mt\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1403607816;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 754;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 2560;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 57;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F58_1006;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F58_1007;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 171; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
